steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/sql-server-location:$SHORT_SHA'
    - '.'
  
# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/sql-server-location:$SHORT_SHA'

# This step stops the database pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Stop Pod
  args:
    - 'scale'
    - 'deploy'
    - 'sql-server-location-test'
    - '--replicas=0'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  

# This step deploys to the Stage environment
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Deploy Test
  args:
  - run
  - --filename=test.yaml
  - --image=gcr.io/$PROJECT_ID/sql-server-location:$SHORT_SHA
  - --output=/tmp/outputstage
  - --location=us-east1-b
  - --cluster=cluster-1  

# This step starts the database pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Scale Pod
  args:
    - 'scale'
    - 'deploy'
    - 'sql-server-location-test'
    - '--replicas=1'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    

# This step triggers the Prod Deployment
- name: 'gcr.io/cloud-builders/gcloud'
  id: Trigger Prod
  args:
  - builds
  - submit
  - --config
  - cloudbuild-prod.yaml
  - --substitutions
  - _SHORT_SHA=$SHORT_SHA
  - .
